name: PMDK_runners

on: [push, pull_request]

jobs:
  linux:
    name: PMDK_runners
    if: github.repository == 'tszczyp/pmdk'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [[self-hosted, opensuse]]
    env:
      WORKDIR: utils/gha-runners

    steps:

        - name: Clone the git repo
          uses: actions/checkout@v2

        - name: Get system information
          run: |
            ./$WORKDIR/get-system-info.sh

        - name: Build
          run: |
            ./$WORKDIR/build-pmdk.sh

        - name: Create testconfig files
          run: |
            ./$WORKDIR/create-testconfig.sh

        - name: Show testconfig file
          run: |
            cat src/test/testconfig.sh

        - name: Run failing tests
          run: |
            cd src/test
            ./RUNTESTS obj_sync